-- 코드를 입력하세요
SELECT TITLE, BOARD.BOARD_ID, REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, TO_CHAR(REPLY.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE 
FROM USED_GOODS_BOARD BOARD 
JOIN USED_GOODS_REPLY REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE TO_CHAR(BOARD.CREATED_DATE,'YYYY-MM-DD') LIKE '2022-10%'
ORDER BY REPLY.CREATED_DATE ASC, TITLE ASC;